### ISSUE TITLE
Dynamic information is wrong

### ISSUE THREAD

**Issue by AlvaroMartinezR** [roboticslab-uc3m/teo-software-manual#15]
I realized the dynamic information about TEO from SolidWorks is not completely accurate:

- The center of mass is not related to the coordinate axis of each piece in some cases, but to the global CoC.

- SolidWorks works with different CoC other than the rest of the models we have of TEO (seen in the next image, bottom left corner). For example, here Y is the vertical axis whereas in the rest the vertical is Z. Therefore all information in  teo-software-manual/assets/teo-dynamic-information.md has its axis changed. 
![image](https://user-images.githubusercontent.com/26522251/33210554-09023116-d11b-11e7-9fdf-476538f33df7.png)

I just wanted to make it known in case someone wanted to use them. In the meantime,  teo-simox-models/doc/CoM simox.csv can be used, but I am pending for the next week to use ods2md in this file.

**Comment by jgvictores** [comment]
I've been looking at [teo-simox-models/doc/CoM simox.csv](https://github.com/roboticslab-uc3m/teo-simox-models/blob/aab15379813f1f69af9d526cfb6f7b0d056d42cd/doc/CoM%20simox.csv) and can say that `.csv` is a perfectly acceptable format to be used directly (instead of `.md`, and no passing through `.ods` or therefore `ods2md`). Essentially what we are looking for is:
- Easy for a human to read.
- Easy for a machine to parse.
- Nice GitHub preview is a plus.

This criteria is met for `.csv` (even have the nice preview on the Desktop version of GitHub).

**Comment by AlvaroMartinezR** [comment]
Now is corrected and better presented [here](https://github.com/roboticslab-uc3m/teo-software-manual/blob/master/assets/teo-dynamic-information.md). 

I close the issue.
