### ISSUE TITLE
Document dual/multi-boot on TEO PCs

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-software-manual#23]
Note to self: Document dual/multi-boot on TEO PCs, see https://github.com/roboticslab-uc3m/teo-main/issues/26#issuecomment-353330145

**Comment by rsantos88** [comment]
Regarding this issue,  the dual boot was overwritten in the manipulation computer and in the locomotion computer. Both have exclusively installed Ubuntu 16.04.6 LTS. No more dual-boot. Only Teo-head contains two ubuntu versions, the last installed Ubuntu 16.04 and the old version (I think ubuntu 15.04) because it was the last computer to be updated.

**Comment by PeterBowman** [comment]
Obsolete, no actionable here.
